const Cart = require('../models/Cart');
const Product = require('../models/Product');

exports.get = async (req, res, next) => { try { const cart = await Cart.findOne({ userId: req.user._id }).populate('items.productId'); res.json({ success: true, data: cart || { userId: req.user._id, items: [] } }); } catch (error) { next(error); } };
exports.add = async (req, res, next) => {
  try { const { productId, quantity } = req.body; const product = await Product.findById(productId); if (!product) return res.status(404).json({ success: false, message: 'Product not found', errorCode: 'NOT_FOUND' }); if (quantity > product.stock) return res.status(400).json({ success: false, message: 'Quantity exceeds live stock', errorCode: 'INSUFFICIENT_STOCK' }); const cart = await Cart.findOneAndUpdate({ userId: req.user._id }, { $setOnInsert: { userId: req.user._id } }, { upsert: true, new: true }); const item = cart.items.find((entry) => entry.productId.toString() === productId); if (item) { if (item.quantity + quantity > product.stock) return res.status(400).json({ success: false, message: 'Quantity exceeds live stock', errorCode: 'INSUFFICIENT_STOCK' }); item.quantity += quantity; } else cart.items.push({ productId, quantity }); await cart.save(); await cart.populate('items.productId'); res.status(201).json({ success: true, data: cart }); } catch (error) { next(error); }
};
exports.update = async (req, res, next) => { try { const cart = await Cart.findOne({ userId: req.user._id }); const item = cart?.items.id(req.params.itemId); if (!item) return res.status(404).json({ success: false, message: 'Cart item not found', errorCode: 'NOT_FOUND' }); const product = await Product.findById(item.productId); if (!product) return res.status(404).json({ success: false, message: 'Product not found', errorCode: 'NOT_FOUND' }); if (req.body.quantity > product.stock) return res.status(400).json({ success: false, message: 'Quantity exceeds live stock', errorCode: 'INSUFFICIENT_STOCK' }); item.quantity = req.body.quantity; await cart.save(); res.json({ success: true, data: cart }); } catch (error) { next(error); } };
exports.remove = async (req, res, next) => { try { const cart = await Cart.findOne({ userId: req.user._id }); const item = cart?.items.id(req.params.itemId); if (!item) return res.status(404).json({ success: false, message: 'Cart item not found', errorCode: 'NOT_FOUND' }); item.deleteOne(); await cart.save(); res.json({ success: true, data: cart }); } catch (error) { next(error); } };
